export type ColorPalette = {
  primary: string;
  primaryDark: string;
  secondary: string;
  secondaryDark: string;
  success: string;
  warning: string;
  error: string;
  info: string;
  white: string;
  black: string;
  gray100: string;
  gray200: string;
  gray300: string;
  gray400: string;
  gray500: string;
  gray600: string;
  gray700: string;
  gray800: string;
  gray900: string;
  textPrimary: string;
  textSecondary: string;
  textInverse: string;
  background: string;
  backgroundAlt: string;
  backgroundInverse: string;
  border: string;
  borderStrong: string;
  overlay: string;
  [key: string]: string;
};
